---
- name: configure webserver with tls
  hosts: nodes
  gather_facts: true
  become: true
  vars:
    nginx_port_with_tls: 443
  tasks:
    - name: create nginx repo definition
      copy:
        src: nginx.repo
        dest: /etc/yum.repos.d/nginx.repo
        owner: root
        group: root
        mode: 0644

    - name: install nginx
      yum:
        name: nginx
        update_cache: true
        state: present

    - name: copy main nginx config file
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: Install openssl package
      yum:
        name: ["openssl", "pyOpenSSL"]
        state: "latest"
        update_cache: true
    
    - name: Create ssl directory
      file:
        path: "/etc/nginx/ssl/"
        state: directory
        mode: 0775
   
    - name: Generate Private key
      community.crypto.openssl_privatekey:
        path: "/etc/nginx/ssl/device.key"
    
    - name: Generate CSR
      community.crypto.openssl_csr: 
        path: /etc/nginx/ssl/localhost.csr
        privatekey_path: /etc/nginx/ssl/device.key 
        common_name: mycomp.com 
        country_name: RU
        email_address: mail@mail.com
        organization_name: MyOrg

    # - name: copy file certificate signing request
    #   copy:
    #     src: files/localhost.csr
    #     dest: /etc/nginx/localhost.csr
    #     owner: root
    #     group: root
    #     mode: 0644
    #   notify: restart nginx

    # - name: copy private key  file
    #   copy:
    #     src: files/device.key
    #     dest: /etc/nginx/device.key
    #     owner: root
    #     group: root
    #     mode: 0644
    #   notify: restart nginx

    - name: copy site's nginx config file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/tls.conf
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: Install Python3 for generte SSL cetrificate
      shell: yum install python3 centos-release-ansible-29 -y && yum install ansible-2.9.14 -y 
      args:
        warn: False
 
    - name: Generate a Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
        path: /etc/nginx/localhost.crt
        privatekey_path: /etc/nginx/device.key
        csr_path: /etc/nginx/localhost.csr
        provider: selfsigned
      notify: restart nginx

    - name: copy index.html
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0644
      notify: restart nginx

    - name: ensure nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: true

    - name: insert firewalld rule for nginx
      firewalld:
        port: "{{ nginx_port_with_tls }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: true

# post_tasks:
#   - name: check web site from control server
#     uri:
#       url: "https://{{ ansible_host }}"
#       return_content: true
#      connection: local
#      register: example_webpage_out
#      failed_when: example_webpage_out.status != 200
#      failed_when: example_webpage_out.content

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
