---
- name: Install 'mariadb-server' and 'MySQL-python' packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - mariadb-server
    - MySQL-python
  tags: mariadb
  become: true

- name: Ensure 'mariadb' service start and enable
  ansible.builtin.service:
    name: "mariadb"
    enabled: yes
    state: "started"
  tags: mariadb
  become: true  

- name: Set up root user
  community.mysql.mysql_user:
    name: "root"
    password: "{{ db_root_password }}"
    login_user: "root"
    login_password: "{{ db_root_password }}"
    check_implicit_admin: true
  no_log: True
  tags: mariadb
  become: true

- name: Create "{{ db_name }}" database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: "present"
    login_user: "root"
    login_password: "{{ db_root_password }}"
  no_log: True
  tags: mariadb

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ""
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
  no_log: True
  tags: mariadb
  become: true

- name: Remove test database
  community.mysql.mysql_db:
    name: "test"
    state: absent
    login_user: "root"
    login_password: "{{ db_root_password }}"
  no_log: True
  tags: mariadb

- name: >
    Create database user "{{ db_user }}" with "{{ db_password }}"
    and "{{ db_name }}".*:ALL privelege
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    login_user: "root"
    login_password: "{{ db_root_password }}"
  no_log: True
  tags: mariadb
